# Build configuration for code generation
targets:
  $default:
    builders:
      # Injectable code generation
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          # Only scan files with DI annotations, exclude constants, config, entities, models, states, events, errors
          exclude:
            - "lib/core/constants/**"
            - "lib/core/error/**"
            - "lib/config/routes/**"
            - "lib/**/entities/**"
            - "lib/**/models/**"
            - "lib/**/bloc/*_state.dart"
            - "lib/**/bloc/*_event.dart"
            - "lib/**/presentation/pages/**"
            - "lib/**/presentation/widgets/**"
            - "lib/main.dart"
        options:
          # Generate relative imports
          auto_register: true

      # JSON serialization code generation
      json_serializable:
        enabled: true
        options:
          # Automatically generate fromJson and toJson
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true

      # Hive type adapter generation
      hive_generator:hive_generator:
        enabled: true
        options:
          # Generate Hive type adapters
          auto_register: true
